A concept for manual intervention, in line with readme changes

diff --git a/10conf-d.yml b/10conf-d.yml
--- a/10conf-d.yml
+++ b/10conf-d.yml
@@ -18,6 +18,7 @@ data:
     wsrep_on=ON
     wsrep_provider="/usr/lib/galera/libgalera_smm.so"
     #init-new-cluster#wsrep_new_cluster=true
+    #init-recovery#wsrep_provider_options="pc.recovery=TRUE"
     #init-bootstrap#wsrep_provider_options="pc.bootstrap=TRUE;pc.wait_prim=FALSE"
     wsrep_cluster_address="gcomm://mariadb-0.mariadb,mariadb-1.mariadb,mariadb-2.mariadb"
     binlog_format=ROW
@@ -59,7 +60,7 @@ data:
 
     [mariadb-10.2]
   init.sh: |
-    #!/bin/sh
+    #!/bin/bash
     set -x
 
     HOST_ID=${HOSTNAME##*-}
@@ -71,27 +72,56 @@ data:
 
     [ -z "$DATADIR" ] && exit "Missing DATADIR variable" && exit 1
 
-    # https://github.com/docker-library/mariadb/commit/f76084f0f9dc13f29cce48c727440eb79b4e92fa#diff-b0fa4b30392406b32de6b8ffe36e290dR80
-    if [ ! -d "$DATADIR/mysql" ]; then
-      echo "No database in $DATADIR; configuring $POD_NAME for initial start"
+    SUGGEST_EXEC_COMMAND="kubectl --namespace=$POD_NAMESPACE exec -c init-config $POD_NAME --"
 
-      if [ $HOST_ID -eq 0 ]; then
-        sed -i 's|^#init-new-cluster#||' /etc/mysql/conf.d/galera.cnf
-        # ... should log:
-        #[Note] WSREP: 'wsrep-new-cluster' option used, bootstrapping the cluster
-        #[Note] WSREP: Setting initial position to 00000000-0000-0000-0000-000000000000:-1
-      fi
-    else
-      if [ $HOST_ID -eq 0 ]; then
-        echo "This is the 1st statefulset pod, but with data. Checking if the statefulset is down ..."
-        getent hosts mariadb
-        [ $? -eq 2 ] && {
-          echo "Yes, guessing we have to bootstrap the galera cluster"
-          #sed -i 's|^#init-bootstrap#||' /etc/mysql/conf.d/galera.cnf
-          #sed -i 's|wsrep_cluster_address=.*|wsrep_cluster_address="gcomm://mariadb-anystatus?pc.wait_prim=FALSE\&pc.bootstrap=TRUE"|' /etc/mysql/conf.d/galera.cnf
-          sed -i 's|^#init-new-cluster#||' /etc/mysql/conf.d/galera.cnf
-        }
-      fi
+    function wsrepNewCluster {
+      sed -i 's|^#init-new-cluster#||' /etc/mysql/conf.d/galera.cnf
+    }
+
+    function wsrepRecovery {
+      sed -i 's|^#init-recovery#||' /etc/mysql/conf.d/galera.cnf
+    }
+
+    [[ $STATEFULSET_SERVICE = mariadb.* ]] || echo "WARNING: unexpected service name $STATEFULSET_SERVICE, Peer detection below may fail falsely."
+
+    if [ $HOST_ID -eq 0 ]; then
+      echo "This is the 1st statefulset pod. Checking if the statefulset is down ..."
+      getent hosts mariadb
+      [ $? -eq 2 ] && {
+        # https://github.com/docker-library/mariadb/commit/f76084f0f9dc13f29cce48c727440eb79b4e92fa#diff-b0fa4b30392406b32de6b8ffe36e290dR80
+        if [ ! -d "$DATADIR/mysql" ]; then
+          echo "No database in $DATADIR; configuring $POD_NAME for initial start"
+          wsrepNewCluster
+        else
+          set +x
+          echo "----- ACTION REQUIRED -----"
+          echo "No peers found, but data exists. To start in wsrep_new_cluster mode, run:"
+          echo "  $SUGGEST_EXEC_COMMAND touch /tmp/confirm-wsrep-new-cluster"
+          echo "Or to start in recovery mode, to see replication state, run:"
+          echo "  $SUGGEST_EXEC_COMMAND touch /tmp/confirm-recovery-mode"
+          echo "Or to try a regular start (for example after recovery + manual intervention), run:"
+          echo "  $SUGGEST_EXEC_COMMAND touch /tmp/confirm-resume"
+          echo "Waiting for response ..."
+          while [ ! -f /tmp/confirm-resume ]; do
+            sleep 1
+            if [ "$AUTO_NEW_CLUSTER" = "yes" ]; then
+              echo "The AUTO_NEW_CLUSTER env was set to $AUTO_NEW_CLUSTER, so won't wait for confirmation"
+              wsrepNewCluster
+              touch /tmp/confirm-resume
+            elif [ -f /tmp/confirm-wsrep-new-cluster ]; then
+              echo "Confirmation received. Resuming new cluster start ..."
+              wsrepNewCluster
+              touch /tmp/confirm-resume
+            elif [ -f /tmp/confirm-recovery-mode ]; then
+              echo "Confirmation received. Resuming in recovery mode."
+              echo "Note: for the other pods you need to edit OrderedReady and add a command: --wsrep-recover"
+              wsrepRecovery
+              touch /tmp/confirm-resume
+            fi
+          done
+          set -x
+        fi
+      }
     fi
 
     # https://github.com/docker-library/mariadb/blob/master/10.2/docker-entrypoint.sh#L62
